### PR TITLE
Terraform 0.8.x compatibility updates

### PR DESCRIPTION
**Pull request by cristobal23**
Update modules to use terraform 0.8.x order of operations on math operators.

For `count` to be either `0` or `1` in

- terraform versions < 0.8.0:
```
count = "${signum(length(var.min_elb_capacity)) + 1 % 2}"
```

- terraform versions >= 0.8.0:
```
count = "${(signum(length(var.min_elb_capacity)) + 1) % 2}"
```

### CODE REVIEW

**Comment by disaac** [comment]
The parenthesis might even be backward compatible with 0.7. If they are thats a harmless fix for sure.

**Comment by cristobal23** [comment]
Yay! thanks @blakeneyops! Ran the build and passed the checks

**Comment by cristobal23** [comment]
This PR is going to need one more thing! It needs the ability to specify [a list for suspended_processes](https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html#suspended_processes)

**Comment by blakeneyops** [comment]
All addressed in #18

**Pull request closed without merging**
